### PR TITLE
Adding ROUGE Score Testing w/ Abstract, Using new tokenizer, Removing Improper Sentences from Body Rather than Summary Text

### PR DESCRIPTION
**Pull request by ruizhann**

### CODE REVIEW

**Comment by ruizhann** [comment]
ROUGE Scores for Bird's PDF is reaching 0.5-0.6. NaturePDF is 0.3-0.4 (but w/o abstract, only using first few sentences in PDF).

**Comment by dengpris** [comment]
image

Generated summary keeps using "e etc," any idea why?

**Comment by ruizhann** [comment]
What's the original sentence? Or what PDF are you using? (i assume e ect -> 'effect')

**Comment by ruizhann** [comment]
Adding new verification flow for ROUGE scores including pulling abstract from cermine and appending it to body text to be fed into summarizer. Added flag to enable verification flow in viewer.js.

**Comment by ruizhann** [comment]
Not the best scores but better than our initial.
image

**Review by cuevasm2 — APPROVED** [review]

**Pull request merged**
